"""Add role and difficulty fields

Revision ID: 1dffb502c0f3
Revises: c40ef32dad8c
Create Date: 2026-02-08 11:47:55.374183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dffb502c0f3'
down_revision: Union[str, Sequence[str], None] = 'c40ef32dad8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('role_category', sa.String(), nullable=True))
    op.add_column('interviews', sa.Column('sub_role', sa.String(), nullable=True))
    op.add_column('interviews', sa.Column('difficulty_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'difficulty_level')
    op.drop_column('interviews', 'sub_role')
    op.drop_column('interviews', 'role_category')
    # ### end Alembic commands ###
