"""Add resume analysis fields

Revision ID: 36ccf1a3a46a
Revises: 1dffb502c0f3
Create Date: 2026-02-08 11:54:01.239544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36ccf1a3a46a'
down_revision: Union[str, Sequence[str], None] = '1dffb502c0f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('resume_text', sa.Text(), nullable=True))
    op.add_column('interviews', sa.Column('ats_score', sa.Float(), nullable=True))
    op.add_column('interviews', sa.Column('resume_analysis', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'resume_analysis')
    op.drop_column('interviews', 'ats_score')
    op.drop_column('interviews', 'resume_text')
    # ### end Alembic commands ###
