"""Restore missing sub_role column

Revision ID: 74ccd40b4431
Revises: 876cf91e80ec
Create Date: 2026-02-08 18:40:05.666579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74ccd40b4431'
down_revision: Union[str, Sequence[str], None] = '876cf91e80ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('sub_role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'sub_role')
    # ### end Alembic commands ###
