"""Add Panel, Tone, and Roadmap tables

Revision ID: 876cf91e80ec
Revises: 98fc1646bf36
Create Date: 2026-02-08 15:41:02.740002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '876cf91e80ec'
down_revision: Union[str, Sequence[str], None] = '98fc1646bf36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_roadmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('interview_id', sa.Integer(), nullable=True),
    sa.Column('focus_areas', sa.JSON(), nullable=True),
    sa.Column('curriculum', sa.JSON(), nullable=True),
    sa.Column('resources', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_roadmaps_id'), 'learning_roadmaps', ['id'], unique=False)
    op.add_column('interviews', sa.Column('is_panel', sa.Integer(), nullable=True))
    op.add_column('interviews', sa.Column('tone_analysis', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'tone_analysis')
    op.drop_column('interviews', 'is_panel')
    op.drop_index(op.f('ix_learning_roadmaps_id'), table_name='learning_roadmaps')
    op.drop_table('learning_roadmaps')
    # ### end Alembic commands ###
