"""Add questions_count to track multi-turn rounds

Revision ID: 8a57e6a8cee4
Revises: bce270eec3ef
Create Date: 2026-02-08 19:05:56.815859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a57e6a8cee4'
down_revision: Union[str, Sequence[str], None] = 'bce270eec3ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('questions_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'questions_count')
    # ### end Alembic commands ###
