"""Add company and round tracking

Revision ID: 98fc1646bf36
Revises: 36ccf1a3a46a
Create Date: 2026-02-08 15:32:35.032596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98fc1646bf36'
down_revision: Union[str, Sequence[str], None] = '36ccf1a3a46a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('target_company', sa.String(), nullable=True))
    op.add_column('interviews', sa.Column('interview_round', sa.String(), nullable=True))
    op.add_column('interviews', sa.Column('current_round_number', sa.Integer(), nullable=True))
    op.drop_column('interviews', 'sub_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('sub_role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('interviews', 'current_round_number')
    op.drop_column('interviews', 'interview_round')
    op.drop_column('interviews', 'target_company')
    # ### end Alembic commands ###
