"""Add multi-round tracking fields

Revision ID: a15dc710d08e
Revises: f44c6d86d643
Create Date: 2026-02-09 17:51:03.492309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a15dc710d08e'
down_revision: Union[str, Sequence[str], None] = 'f44c6d86d643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('rounds_completed', sa.JSON(), nullable=True))
    op.add_column('interviews', sa.Column('round_scores', sa.JSON(), nullable=True))
    op.add_column('interviews', sa.Column('overall_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'overall_status')
    op.drop_column('interviews', 'round_scores')
    op.drop_column('interviews', 'rounds_completed')
    # ### end Alembic commands ###
