"""Make user_id nullable for guest sessions

Revision ID: bce270eec3ef
Revises: 74ccd40b4431
Create Date: 2026-02-08 18:43:09.991762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce270eec3ef'
down_revision: Union[str, Sequence[str], None] = '74ccd40b4431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
