"""Add interviewer_name to store AI personality selection

Revision ID: f44c6d86d643
Revises: 8a57e6a8cee4
Create Date: 2026-02-08 19:38:13.933512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f44c6d86d643'
down_revision: Union[str, Sequence[str], None] = '8a57e6a8cee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('interviewer_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'interviewer_name')
    # ### end Alembic commands ###
